const products = [
  {
    id: "rank-vip",
    name: "VIP",
    description: "Unlock exclusive perks and stand out from the crowd with the VIP rank.",
    price: 399,
    category: "ranks",
    featured: false,
    color: "#22c55e",
    perks: [
      "Green name color in chat",
      "Access to /fly in lobby",
      "3 home locations",
      "VIP-only kit (weekly)",
      "Priority queue access",
    ],
  },
  {
    id: "rank-vip-plus",
    name: "VIP+",
    description: "Everything in VIP plus additional exclusive commands and cosmetics.",
    price: 799,
    category: "ranks",
    featured: false,
    color: "#86efac",
    perks: [
      "Everything in VIP",
      "Aqua name color in chat",
      "5 home locations",
      "Access to /trail effects",
      "VIP+ kit (weekly)",
      "Exclusive cosmetic hat",
    ],
  },
  {
    id: "rank-elite",
    name: "Elite",
    description: "A mid-tier rank with powerful in-game advantages and style.",
    price: 1199,
    category: "ranks",
    featured: true,
    color: "#facc15",
    perks: [
      "Everything in VIP+",
      "Gold name color in chat",
      "8 home locations",
      "Access to /disguise",
      "Elite kit (weekly)",
      "Exclusive particle effects",
      "Early access to new features",
    ],
  },
  {
    id: "rank-legend",
    name: "Legend",
    description: "Become a legend on CrisisMC with top-tier perks and recognition.",
    price: 1999,
    category: "ranks",
    featured: true,
    color: "#f97316",
    perks: [
      "Everything in Elite",
      "Orange name color in chat",
      "15 home locations",
      "Access to /pets",
      "Legend kit (weekly)",
      "Custom join message",
      "Exclusive Legend cosmetics",
      "Access to Legend-only events",
    ],
  },
  {
    id: "rank-titan",
    name: "Titan",
    description: "The ultimate rank. Rule CrisisMC with unrivaled power and prestige.",
    price: 3999,
    category: "ranks",
    featured: true,
    color: "#a855f7",
    perks: [
      "Everything in Legend",
      "Purple name color in chat",
      "Unlimited home locations",
      "Access to /god mode (survival)",
      "Titan kit (weekly)",
      "Custom prefix",
      "Exclusive Titan-only world access",
      "Monthly in-game credits",
      "Direct Discord support channel",
    ],
  },
  {
    id: "key-crate",
    name: "Crate Key Bundle",
    description: "Open mystery crates for rare items, weapons, and exclusive loot.",
    price: 249,
    category: "keys",
    featured: false,
    color: "#38bdf8",
    perks: [
      "5 mystery crate keys",
      "Chance for rare enchanted gear",
      "Chance for exclusive cosmetics",
      "Tradeable with other players",
    ],
  },
  {
    id: "currency-pack",
    name: "Coin Pack — 5000",
    description: "Get in-game coins to spend in the player market and shop.",
    price: 329,
    category: "currency",
    featured: false,
    color: "#fbbf24",
    perks: [
      "5000 CrisisCoins added to your account",
      "Use in the in-game shop",
      "Trade with other players",
    ],
  },
];

export const onRequestGet = (): Response =>
  new Response(JSON.stringify(products), {
    headers: { "Content-Type": "application/json" },
  });
